DROP TABLE IF EXISTS STUDENTS;
  
CREATE TABLE STUDENTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  english_marks NUMBER(3,0) NOT NULL,
  science_marks NUMBER(3,0) NOT NULL,
  maths_marks NUMBER(3,0) NOT NULL  

);

DROP TABLE IF EXISTS STUDENTS_TOTAL;



